config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
 
  get 'home/about'
  root 'home#index'
  get 'admin/dashboard/graph'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
  end

  authenticated :user do
    root to: 'home#index', as: :authenticated_root
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
# app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
   
  
    validates :first_name, :last_name, presence: true
  end
  

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_many :friends


  def admin?
    self.admin
  end
end

app/controllers/admin/dashboard_controller.rb
# app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
    layout 'admin'
  
    before_action :authenticate_user!
    before_action :authenticate_admin!
  
    def index

       
    end
    def graph
      @friends_by_day = Friend.group_by_day_of_week(:created_at, format: "%a").count
      @total_friends = Friend.count 
      @last_friend_date = Friend.order(created_at: :desc).first&.created_at
    end
  
    private
  
    def authenticate_admin!
      redirect_to root_path unless current_user&.admin?
    end
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :redirect_admin, if: :user_signed_in?

    private
  
    def redirect_admin
        if current_user.admin? && request.path == authenticated_root_path
          redirect_to admin_dashboard_path
        end
      end
    
      def after_sign_in_path_for(resource)
        if resource.admin?
          admin_dashboard_path
        else
          authenticated_root_path
        end
      end
    end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def About
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/dashboard/graph.html.erb
<%= line_chart @friends_by_day %>
<p>Total Friends: <%= @total_friends %></p>
<p>Last Friend Added On: <%= @last_friend_date ? @last_friend_date.strftime("%B %d, %Y") : "No friends added yet" %></p>

app/views/admin/dashboard/index.html.erb
<p> Welcome Admin </p>

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone Number" %>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
  
  
  <div class="field form-group">
    
    <%= form.hidden_field :user_id, id: :friend_user_id, value: current_user.id %>

  </div>
  
<br/>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>
<br/>
<%= render 'form', friend: @friend %>

<br/>
<%= link_to 'Show', @friend, class:"btn btn-secondary" %>

<%= link_to 'Delete', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

<%= link_to 'Back', friends_path, class:"btn btn-dark" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th> </th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
        <tr>
          <td>
<%= link_to friend.first_name + ' ' + friend.last_name, friend %>


          </td>
          
          <td><%= friend.email %></td>
          <td><%= friend.phone %></td>
          <td><%= friend.twitter %></td>
          
          
          
          
          
          <td><%= link_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
<% else %>

<h1>Hello World!</h1>
This is my first Rails Webpage...

<% end %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
  </h1>
  <p class="lead">
    <%= @friend.email %>  | 
    <%= @friend.phone %>  |  
    <%= @friend.twitter %>

  </p>
  <br/>
<div class="btn-group" role="group" >
 <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
   <%= button_to 'Delete', @friend, method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } }, class: "btn btn-danger mx-1" %>
  <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-secondary" %>



   
 
  </div>

</div>

app/views/home/_footer.html.erb
 <footer style="position:absolute; bottom:0; width:100%;"class="footer">
      <!-- Grid container -->
      <div class="container pt-4">
        <!-- Section: Social media -->
        <section class="mb-4">
          <!-- Facebook -->
          <a
            class="btn btn-link btn-floating btn-lg text-body m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
          ><i class="fab fa-facebook-f"></i></a>

          <!-- Twitter -->
          <a
            class="btn btn-link btn-floating btn-lg text-body m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
          ><i class="fab fa-twitter"></i></a>

          <!-- Google -->
          <a
            class="btn btn-link btn-floating btn-lg text-body m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
          ><i class="fab fa-google"></i></a>

          <!-- Instagram -->
          <a
            class="btn btn-link btn-floating btn-lg text-body m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
          ><i class="fab fa-instagram"></i></a>

          <!-- Linkedin -->
          <a
            class="btn btn-link btn-floating btn-lg text-body m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
          ><i class="fab fa-linkedin"></i></a>

          <!-- Github -->
          <a
            class="btn btn-link btn-floating btn-lg text-body m-1"
            href="#!"
            role="button"
            data-mdb-ripple-color="dark"
          ><i class="fab fa-github"></i></a>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 Copyright:
        <a class="text-body" href="github.com/macOS-M">macOS-M</a>
      </div>
      <!-- Copyright -->
    </footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <div class="container-fluid">
   <%= link_to 'Friends', root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'About Us', home_about_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
            <%= link_to 'Friends', friends_path, class: "nav-link"%>
        </li>

      <% if user_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class: "nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
        </li>  
        <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link"%>
        </li>
                
        <% else %>
        <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link"%>
        </li>   
        <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link"%>
        </li> 

   
      <%end%>  
    
           
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/_headerAdmin.html.erb
<script>
document.addEventListener('DOMContentLoaded', () => {
    const currentPath = window.location.pathname;
    document.querySelectorAll('.nav-link').forEach(link => {
        const linkPath = new URL(link.href).pathname;
        link.classList.remove('active');
        
        // Compare the paths
        if (linkPath === currentPath) {
            link.classList.add('active');
        }
    });
});


</script>
<div class="position-fixed d-flex flex-column p-3 bg-light" style="width: 250px; height: 100vh;">
    <div class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none" style="user-select: none;">
        <span class="fs-4">Admin Dashboard</span>
    </div>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Graphs", admin_dashboard_graph_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
        </li>
    </ul>
</div>

app/views/home/about.html.erb
<h1> About us... </h1>

app/views/home/index.html.erb
<h1>Hello Wolrd </h1>
This is my first Rails Webpage...

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/admin.html.erb
<!-- app/views/layouts/admin.html.erb -->
<!DOCTYPE html>
<html>
<head>
  <title>Admin Dashboard</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>
<body>
  <%= render 'home/headerAdmin' %>
  <div class ="container">
  <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
  
    <%= yield %>
    </div>
  <%=render 'home/footer'%>

  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'home/header' %>
  <div class ="container">
  <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
  
    <%= yield %>
    </div>
    <%=render 'home/footer'%>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>